name: snowflake-liquibase-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'MasterLog/deploy/**'

  # Allows you to run this workflow manually from the Actions tab
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Run 'Liquibase status' in a Dcoker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.SF_URL }} --changeLogFile=/MasterLog/masterChangelog.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --driver=${{secrets.SF_DRIVER}} --defaultSchemaName=${{ secrets.SF_SCHEMA }} status
        
    - name: Run 'Liquibase update' in a Docker Container
      uses: docker://liquibase/liquibase:latest
      with:
        args: --url=${{ secrets.SF_URL }} --changeLogFile=/MasterLog/masterChangelog.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --driver=${{secrets.SF_DRIVER}} --defaultSchemaName=${{ secrets.SF_SCHEMA }} --logLevel=debug update
